---
- name: Verify
  hosts: all
  vars:
    ruby_version: 3.3.5
  roles:
    - jobscore.ruby
  post_tasks:
    - name: Check ruby version
      ansible.builtin.command: "ruby -v --yjit"
      register: version_check
      changed_when: false

    - name: Ensure the right Ruby version is installed
      ansible.builtin.fail:
        msg: "The installed ruby version is different from the expected. Expected {{ ruby_version }} got {{ version_check.stdout }}"
      when: ruby_version not in version_check.stdout

    - name: Ensure YJIT is enabled
      ansible.builtin.fail:
        msg: "The installed ruby version is different from the expected. Expected {{ ruby_version }} got {{ version_check.stdout }}"
      when:
        - ruby_enable_yjit | bool
        - "'YJIT' not in version_check.stdout"
